max_history = 3

[client]
description = "This is the client side code for LLM Voice Assistant"

[wakeword]
model = "hey jarvis" # Use one of the pretrained models from openWakeWord ("alexa", "hey mycroft" or "hey jarvis") or specify a path to your custom model.
disable_wakeword = false

[vad]
initial_delay = 10.0
delay = 2.0

[chat]
# By default will create a new chat every time the program starts. You can specify a json file here to keep the same chat history across sessions.
history = ""

[system]
system_prompt = "system-prompts/default-prompt.txt"

[stt]
model = "rtlingo/mobiuslabsgmbh-faster-whisper-large-v3-turbo"
api = "http://localhost:8000/v1"
api_key = ""
language = "" # By default Whisper will attempt to automatically determine what language is spoken. You can improve accuracy and latency if you specify a language here (i.e. "en", "es", "ja" or "zh")

[llm]
model = "Qwen3-4B-Instruct-2507-GGUF"
api = "http://localhost:9292/v1"
api_key = ""

[tts]
api = "http://localhost:8000/v1"
api_key = ""
